#
# Build
#

build { core lib/ld  init app/afl++ }

create_boot_directory

#
# Generate config
#

install_config {
<config>
	<parent-provides>
		<service name="LOG"/>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="ROM"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="60"/>
	<start name="afl++">
		<resource name="RAM" quantum="1M"/>
	</start>
</config>}

#
# Boot image
#

build_boot_image [build_artifacts]

run_genode_until forever
