 set build_components {
   core init app/afl++
 }
 build $build_components


 append config {
  <config>
    <parent-provides>
      <service name="ROM"/>
      <service name="RAM"/>
      <service name="IO_MEM"/>
      <service name="IO_PORT"/>
      <service name="CAP"/>
      <service name="PD"/>
      <service name="RM"/>
      <service name="CPU"/>
      <service name="LOG"/>
    </parent-provides>
    <default-route>
      <any-service> <parent/> <any-child/> </any-service>
    </default-route>
    <start name="afl++">
      <resource name="RAM" quantum="6M"/>}
      <provides><service name="Audio_out"/></provides>
    </start>


  </config>}
  install_config $config

  set boot_modules {
    core init libc.lib.so libm.lib.so
  }
  build_boot_image $boot_modules

  run_genode_until forever