build { core init timer lib/ld
        lib/libc lib/vfs
        lib/vfs_jitterentropy
        lib/vfs_pipe
        server/vfs
        afl-fuzz
	    lib/posix
        lib/libm
        test/posix_bin}

import_from_depot [depot_user]/src/vfs_jitterentropy \
                  [depot_user]/src/vfs \
                  [depot_user]/src/vfs_pipe \
                  [depot_user]/src/libc

create_boot_directory

install_config {
<config>
	<parent-provides>
        <service name="LOG"/>
        <service name="PD"/>
        <service name="RM"/>
        <service name="CPU"/>
        <service name="ROM"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> </any-service>
	</default-route>
	<default caps="350"/>
	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Timer"/> </provides>
	</start>

    <start name="vfs" caps="250">
        <resource name="RAM" quantum="500M"/>
        <provides> <service name="File_system"/> </provides>

        <config>
            <vfs>
                <dir name="dev">
                    <log/>
                    <null/>
                    <dir name="pipe"> <pipe/> </dir>
                    <inline name="rtc">2025-01-01 01:01</inline>
                    <jitterentropy name="urandom"/>
                </dir>
                <dir name="output"> <ram/> </dir>
                <dir name="input">
                    <inline name="input-file">content</inline>
                </dir>
                <dir name="binary">
                    <rom name="posix_bin"/>
                </dir>
            </vfs>
            <default-policy root="/" writeable="yes"/>
        </config>
    </start>

	<start name="afl-fuzz">
		<resource name="RAM" quantum="1500M"/>
		<provides> <service name="Shm_Session"/> </provides>
        <config>
            <vfs> <fs/> </vfs>
            <libc stdin="/dev/log" stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc" rng="/dev/urandom" pipe="/dev/pipe" />
        </config>
        <route>
            <service name="File_system"> <child name="vfs" /> </service>
            <service name="ROM" label="/binary/posix_bin"> <parent label="posix_bin"/> </service>
            <service name="Timer"> <child name="timer" /> </service>
            <any-service> <parent/> </any-service>
        </route>
	</start>

</config>}

build_boot_image [build_artifacts]
append qemu_args " -nographic "

run_genode_until "exited with exit value 1*\n" 25
