build { core init timer
        lib/ld
        lib/libc
        lib/vfs
        server/vfs
        test/shm_client
        test/shm_server
      }

import_from_depot [depot_user]/src/vfs \
                  [depot_user]/src/libc

create_boot_directory

install_config {
<config>
    <parent-provides>
        <service name="LOG"/>
        <service name="PD"/>
        <service name="RM"/>
        <service name="CPU"/>
        <service name="ROM"/>
    </parent-provides>

    <default-route>
        <any-service> <any-child/> <parent/> </any-service>
    </default-route>

    <start name="timer" caps="100">
        <resource name="RAM" quantum="1M"/>
        <provides><service name="Timer"/></provides>
        <route>
            <any-service> <parent/> </any-service>
        </route>
    </start>

    <start name="vfs" caps="250">
        <resource name="RAM" quantum="200M"/>
		<provides> <service name="File_system"/> </provides>

		<config>
		    <vfs> <dir name="dev"> <log/> </dir> </vfs>
		    <default-policy root="/" writeable="yes"/>
		</config>
    </start>

    <start name="afl-shm-server" caps="100">
        <resource name="RAM" quantum="200M"/>
		<provides> <service name="Shm_Session"/> </provides>
        <config>
            <vfs> <fs/> </vfs>
            <libc stdin="/dev/log" stdout="/dev/log" stderr="/dev/log" />
        </config>
        <route>
            <service name="File_system"> <child name="vfs" /> </service>
            <any-service> <parent/> </any-service>
        </route>
    </start>

    <start name="afl-shm-client" caps="200">
        <resource name="RAM" quantum="150M"/>
        <config>
            <vfs> <fs/>  </vfs>
            <libc stdin="/dev/log" stdout="/dev/log" stderr="/dev/log"/>
        </config>
        <route>
            <service name="File_system"> <child name="vfs" /> </service>
            <service name="Shm_Session"> <child name="afl-shm-server"/> </service>
            <any-service> <parent/> </any-service>
        </route>
    </start>

</config>}

build_boot_image [build_artifacts]
append qemu_args " -nographic "

run_genode_until "afl-shm test completed.*\n" 250
