build { core lib/ld lib/libc lib/vfs lib/vfs_jitterentropy timer init afl-fuzz }

import_from_depot [depot_user]/src/vfs_jitterentropy \
                  [depot_user]/src/vfs\
                  [depot_user]/src/libc

create_boot_directory

install_config {
<config>
	<parent-provides>
		<service name="LOG"/>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="ROM"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="350"/>
	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Timer"/> </provides>
	</start>
	<start name="afl-fuzz">
		<resource name="RAM" quantum="1000M"/>
        <config>
            <vfs>
                <dir name="dev">
                    <log/>
                    <null/>
                    <inline name="rtc">2025-01-01 01:01</inline>
                    <jitterentropy name="random"/>
                    <jitterentropy name="urandom"/>
                </dir>
                <dir name="output"> <ram/> </dir>
                <dir name="input">
                    <inline name="input-file">content</inline>
                </dir>
            </vfs>
            <libc stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc"  rng="/dev/urandom" />
        </config>
	</start>
</config>}

build_boot_image [build_artifacts]
append qemu_args " -nographic "

# run_genode_until "afl-fuzz test completed.*\n" 25
run_genode_until forever
