build { core lib/ld init test/instrumentation  }

create_boot_directory

install_config {
<config>
	<parent-provides>
		<service name="LOG"/>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="ROM"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="200"/>
	<start name="instrumentation-test-component">
		<resource name="RAM" quantum="50M"/>
	</start>
</config>}

build_boot_image [build_artifacts]

append qemu_args " -nographic "

run_genode_until "Instrumentation test succeeded.*\n" 10
